// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU-8GccJE1mSF0id4usFO9tp18jq2np5Q',
    appId: '1:231892227156:web:351f1919649b909123c9c1',
    messagingSenderId: '231892227156',
    projectId: 'fir-tutorial-d67d4',
    authDomain: 'fir-tutorial-d67d4.firebaseapp.com',
    storageBucket: 'fir-tutorial-d67d4.appspot.com',
    measurementId: 'G-6PJ0LLVKMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3X9MFD7ZCBgsRvqwf5UsxB11YeQyvQOM',
    appId: '1:231892227156:android:81851dec12b60c4d23c9c1',
    messagingSenderId: '231892227156',
    projectId: 'fir-tutorial-d67d4',
    storageBucket: 'fir-tutorial-d67d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjFoRPxG7iS75Cwz92hGvC3IwwlQf1FLU',
    appId: '1:231892227156:ios:7623d2083ea8a0d023c9c1',
    messagingSenderId: '231892227156',
    projectId: 'fir-tutorial-d67d4',
    storageBucket: 'fir-tutorial-d67d4.appspot.com',
    iosBundleId: 'com.example.firebaseTutorials',
  );
}
